# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BuglyProDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'BuglyPro'
#  pod 'BuglyPro', :podspec=>'https://raw.githubusercontent.com/BuglyDevTeam/BuglyPro-iOS/main/BuglyPro.podspec'
  # Pods for BuglyProDemo

  target 'BuglyProDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BuglyProDemoUITests' do
    # Pods for testing
  end

end
